GUSER=MarcusNg              &&  GREPO=flutter_spotify_ui             && APPNAME=SpotifyClone      && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME
GUSER=RivaanRanawat         &&  GREPO=instagram-flutter-clone        && APPNAME=InstagramClone    && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME
GUSER=abuanwar072           &&  GREPO=E-commerce-App-UI-Flutter      && APPNAME=E-CommerceApp     && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME
GUSER=Ronak99               &&  GREPO=Skype-Clone                    && APPNAME=SkypeClone        && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME
GUSER=roughike              &&  GREPO=inKino                         && APPNAME=InKino            && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME
GUSER=iampawan              &&  GREPO=FlutterStackOverflowApp        && APPNAME=StackOverFlow     && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME
GUSER=nisrulz               &&  GREPO=flutter-examples               && APPNAME=Examples          && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME
GUSER=stonega               &&  GREPO=tsacdop                        && APPNAME=PodcastPlayer     && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME
GUSER=Hash-Studios          &&  GREPO=Prism                          && APPNAME=PinterestClone    && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME
GUSER=hungps                &&  GREPO=flutter_pokedex                && APPNAME=Pokemon           && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME
GUSER=iampawan              &&  GREPO=CryptoApp                      && APPNAME=CryptoApp         && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME
GUSER=searchy2              &&  GREPO=FlutterGames                   && APPNAME=GameStore         && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME
GUSER=rajayogan             &&  GREPO=flutterui-curveddesigns        && APPNAME=NutritionApp      && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME
GUSER=Santos-Enoque         &&  GREPO=uber_clone_with_flutter        && APPNAME=UberClone         && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME
GUSER=iampawan              &&  GREPO=GDG-DevFest-App                && APPNAME=DevFest           && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME
GUSER=abuanwar072           &&  GREPO=Furniture-App-UI-2-Flutter     && APPNAME=FurnitureApp      && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME
GUSER=theankurkedia         &&  GREPO=newsbuzz                       && APPNAME=NewsAggregator    && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME
GUSER=mcyos118              &&  GREPO=wordPress-flutter              && APPNAME=WordPress         && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME
GUSER=abuanwar072           &&  GREPO=Protfolio-Website-Flutter-Web  && APPNAME=PortfolioWeb      && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME
GUSER=Norbert515            &&  GREPO=BookSearch                     && APPNAME=BookSearch        && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME
GUSER=tavasolireza          &&  GREPO=Hangman-Game-Flutter           && APPNAME=HangmanGame       && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME
GUSER=rodydavis             &&  GREPO=gmail_clone                    && APPNAME=GmailClone        && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME
GUSER=rajayogan             &&  GREPO=FlutterUI---Emojis             && APPNAME=EmojiUI           && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME
GUSER=MarcusNg              &&  GREPO=flutter_facebook_responsive_ui && APPNAME=FacebookClone     && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME
GUSER=mdanics               &&  GREPO=fluttergram                    && APPNAME=Fluttergram       && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME
GUSER=Hritik-Chaurasia      &&  GREPO=Lavender                       && APPNAME=VideoStream       && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME
GUSER=MarcusNg              &&  GREPO=flutter_netflix_responsive_ui  && APPNAME=NetflixUI         && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME
GUSER=matthewtory           &&  GREPO=trinity-orientation-2018       && APPNAME=TrinityCollege    && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME
GUSER=FilledStacks          &&  GREPO=flutter-tutorials              && APPNAME=TikTokUI          && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME
GUSER=MarcusNg              &&  GREPO=flutter_chat_ui                && APPNAME=ChatApp           && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME
GUSER=MarcusNg              &&  GREPO=flutter_swarm_game             && APPNAME=SwarmGame         && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME
GUSER=MarcusNg              &&  GREPO=flutter_voice                  && APPNAME=Speech2TextApp    && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME
GUSER=boeledi               &&  GREPO=flutter_crush                  && APPNAME=CrushGame         && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME
GUSER=iampawan              &&  GREPO=FlutterWhatsAppClone           && APPNAME=WhatsAppClone     && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME
GUSER=MarcusNg              &&  GREPO=flutter_clubhouse_ui           && APPNAME=ClubHouseClone    && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME
GUSER=jesusrp98             &&  GREPO=spacex-go                      && APPNAME=SpaceXGo          && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME
GUSER=boyan01               &&  GREPO=flutter-tetris                 && APPNAME=TetrisGame        && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME
GUSER=mafreud               &&  GREPO=proximity                      && APPNAME=Widgets           && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME
GUSER=iampawan              &&  GREPO=FlutterTicTacToe               && APPNAME=TicTacToeGame     && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME
GUSER=deven98               &&  GREPO=FlutterSolitaire               && APPNAME=SolitaireGame     && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME
GUSER=rodydavis             &&  GREPO=flutter_piano                  && APPNAME=PocketPiano       && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME
GUSER=janoodleFTW           &&  GREPO=timy-messenger                 && APPNAME=MessengerApp      && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME
GUSER=sergiandreplace       &&  GREPO=flutter_planets_tutorial       && APPNAME=PlanetEducation   && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME
GUSER=abuanwar072           &&  GREPO=E-commerce-Complete-Flutter-UI && APPNAME=E-CommerceApp2    && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME
GUSER=putraxor              &&  GREPO=flutter-login-ui               && APPNAME=CleanLoginUI      && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME
GUSER=iampawan              &&  GREPO=Flutter-Music-Player           && APPNAME=MusicPlayerApp    && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME
GUSER=abuanwar072           &&  GREPO=Recipe-App---Flutter-UI        && APPNAME=RecipeApp         && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME
GUSER=MDSADABWASIM          &&  GREPO=You                            && APPNAME=WhatAboutYou      && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME
GUSER=abuanwar072           &&  GREPO=Meditation-App                 && APPNAME=MeditationApp     && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME
GUSER=Soham-Rakhunde        &&  GREPO=workout_timer                  && APPNAME=WorkoutTimerApp   && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME
GUSER=abuanwar072           &&  GREPO=Travel-App-UI-using-Flutter    && APPNAME=TravelApp         && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME
GUSER=MSzalek-Mobile        &&  GREPO=weight_tracker                 && APPNAME=WeightTracker     && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME
GUSER=abuanwar072           &&  GREPO=Movie-Info---Flutter-UI        && APPNAME=MovieInfoApp      && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME
GUSER=benoitletondor        &&  GREPO=Beer-Me-Up                     && APPNAME=BeerMeup          && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME
GUSER=Samaritan1011001      &&  GREPO=Trovami                        && APPNAME=LiveLocShareApp   && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME
GUSER=brinesoftwares        &&  GREPO=Flutter-AI-Rubik-cube-Solver   && APPNAME=RubikCubeSolver   && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME
GUSER=abuanwar072           &&  GREPO=Food-Ordering-App              && APPNAME=FoodOrderingApp   && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME
GUSER=aaronoe               &&  GREPO=FlutterCinematic               && APPNAME=CinematicApp      && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME
GUSER=iampawan              &&  GREPO=fluttersignatureview           && APPNAME=SignatureView     && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME
GUSER=anuranBarman          &&  GREPO=2048                           && APPNAME=Game2048          && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME
GUSER=abuanwar072           &&  GREPO=Plant-App-Flutter-UI           && APPNAME=PlantAppUI        && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME
GUSER=redsolver             &&  GREPO=skyfeed                        && APPNAME=SkyFeed           && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME
GUSER=imSanjaySoni          &&  GREPO=Inshorts-Clone-The-News-App    && APPNAME=InShortsClone     && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME
GUSER=MDSADABWASIM          &&  GREPO=Toughest                       && APPNAME=ToughestApp       && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME
GUSER=GitJournal            &&  GREPO=GitJournal                     && APPNAME=GoogleKeepClone   && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME
GUSER=ffactory-ofcl         &&  GREPO=fourinarow-app                 && APPNAME=FourInARowGame    && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME
GUSER=flutter               &&  GREPO=samples                        && APPNAME=Samples           && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME
GUSER=JideGuru              &&  GREPO=FlutterEbookApp                && APPNAME=eBookApp          && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME
# EXTRA ...                                                                                                                                                                                                               
GUSER=JideGuru              &&  GREPO=FlutterFoodybite               && APPNAME=FoodyBite         && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME
GUSER=PoojaB26              &&  GREPO=FlutterBasicWidgets            && APPNAME=BasicWidgets      && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME
GUSER=huextrat              &&  GREPO=TheGorgeousLogin               && APPNAME=GorgeousLogin     && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME
GUSER=solutelabs            &&  GREPO=horizontal_calendar            && APPNAME=CalendarApp       && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME
GUSER=mitesh77              &&  GREPO=Best-Flutter-UI-Templates      && APPNAME=UITemplates       && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME
GUSER=firebase              &&  GREPO=flutterfire                    && APPNAME=FirebasePlugins   && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME
GUSER=lohanidamodar         &&  GREPO=flutter_ui_challenges          && APPNAME=UIChallenges      && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME
GUSER=samarthagarwal        &&  GREPO=FlutterScreens                 && APPNAME=UIScreens         && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME
GUSER=Sangwan5688           &&  GREPO=BlackHole                      && APPNAME=BlackHole         && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME
GUSER=TheAlphamerc          &&  GREPO=flutter_ecommerce_app          && APPNAME=E-CommerceApp3    && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME
GUSER=TheAlphamerc          &&  GREPO=flutter_twitter_clone          && APPNAME=TwitterClone      && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME
GUSER=authpass              &&  GREPO=authpass                       && APPNAME=AuthPass          && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME
GUSER=git-touch             &&  GREPO=git-touch                      && APPNAME=GitTouch          && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME
GUSER=iamSahdeep            &&  GREPO=liquid_swipe_flutter           && APPNAME=LiquidSwipe       && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME
GUSER=KhoaSuperman          &&  GREPO=findseat                       && APPNAME=FindSeat          && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME
GUSER=hellobike             &&  GREPO=flutter_thrio                  && APPNAME=ThreeInOne        && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME
GUSER=Tarikul711            &&  GREPO=flutter-food-delivery-app-ui   && APPNAME=FoodDeliveryApp   && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME
GUSER=pawlik92              &&  GREPO=flutter_whirlpool              && APPNAME=WhirlPool         && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME
GUSER=TheAlphamerc          &&  GREPO=flutter_smart_course           && APPNAME=SmartCourse       && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME
GUSER=atornel               &&  GREPO=RestaurantAppUIKit             && APPNAME=RestaurantApp     && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME
GUSER=LiveLikeCounter       &&  GREPO=Flutter-Todolist               && APPNAME=TodoList          && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME
GUSER=vinothvino42          &&  GREPO=SwiggyUI                       && APPNAME=SwiggyUI          && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME
GUSER=CharlyKeleb           &&  GREPO=SocialMedia-App                && APPNAME=Wooble            && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME
GUSER=amangautam1           &&  GREPO=flutter-musicplayer            && APPNAME=MusicPlayerApp2   && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME
GUSER=ketanchoyal           &&  GREPO=Our-E-School                   && APPNAME=eSchoolApp        && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME
GUSER=JideGuru              &&  GREPO=FileX                          && APPNAME=FileX             && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME
GUSER=HitenDev              &&  GREPO=flutter_effects                && APPNAME=Effects           && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME
GUSER=bukunmialuko          &&  GREPO=flutter_ui_kit_obkm            && APPNAME=UISimpleKit       && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME
GUSER=kalismeras61          &&  GREPO=flutter_wallet_ui              && APPNAME=UIWallet          && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME
GUSER=nathansdev            &&  GREPO=ContraFlutterKit               && APPNAME=ContraKit         && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME
GUSER=OpenConsultingGroup   &&  GREPO=Taxi-App                       && APPNAME=TaxiApp           && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME
GUSER=jhomlala              &&  GREPO=feather                        && APPNAME=WeatherApp        && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME
GUSER=brocodev              &&  GREPO=flutter_projects               && APPNAME=SampleProjects    && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME   
GUSER=Origogi               &&  GREPO=Flutter-Credit-Card-Input-Form && APPNAME=CreditCardInput   && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME   
GUSER=leyan95               &&  GREPO=qrcode_scanner                 && APPNAME=QRCodeScanner     && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME     
GUSER=bimsina               &&  GREPO=notes-app                      && APPNAME=NoteTakingApp     && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME    
GUSER=pedromassango         &&  GREPO=xtimer-flutter-app             && APPNAME=TimerApp          && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME  
GUSER=longhoang2984         &&  GREPO=flutter_payment_app_ui         && APPNAME=PaymentApp        && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME   
GUSER=bimsina               &&  GREPO=wallpaper                      && APPNAME=WallpaperApp      && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME     
GUSER=DevStack06            &&  GREPO=Whatsapp-Clone-Flutter         && APPNAME=WhatsAppClone2    && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME    
GUSER=dvmjoshi              &&  GREPO=flutter_firebase               && APPNAME=FirebaseApp       && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME 
GUSER=hamaluik              &&  GREPO=nomdebebe                      && APPNAME=BabyNameApp       && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME    
GUSER=lohanidamodar         &&  GREPO=flutter_opentrivia             && APPNAME=QuizApp           && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME
GUSER=bimsina               &&  GREPO=Matinee-Flutter                && APPNAME=MatineeApp        && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME    
GUSER=lohanidamodar         &&  GREPO=flutter_firebase_starter       && APPNAME=FireBaseStarter   && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME       
GUSER=therezacuet           &&  GREPO=Motion-Tab-Bar                 && APPNAME=MotionTabBar      && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME     
GUSER=HathTech              &&  GREPO=Flutter-Task-App               && APPNAME=TaskApp           && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME  
GUSER=shubhamhackz          &&  GREPO=light_dark_toggle              && APPNAME=LightDarkMode     && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME        
GUSER=Livinglist            &&  GREPO=Hacki                          && APPNAME=HackerNews        && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME       
GUSER=pawlik92              &&  GREPO=flutter_parallax_scroll        && APPNAME=ParallaxScroll    && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME         
GUSER=hackerhgl             &&  GREPO=flutter-ui-designs             && APPNAME=UIDesigns         && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME      
GUSER=theindianappguy       &&  GREPO=TinderGoldRedesign             && APPNAME=TinderRedesign    && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME        
GUSER=kserko                &&  GREPO=CineReel                       && APPNAME=CineReel          && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME      
GUSER=thenifemi             &&  GREPO=PetShop                        && APPNAME=PetShop           && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME       
GUSER=deven98               &&  GREPO=MetaFlutter                    && APPNAME=MetaFlutter       && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME       
GUSER=deven98               &&  GREPO=YouTubeFlutter                 && APPNAME=YoutubeApp        && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME       
GUSER=lohanidamodar         &&  GREPO=flutter_audiobooks_app         && APPNAME=AudioBooks        && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME          
GUSER=naveenjujaray         &&  GREPO=DeveloperFolio                 && APPNAME=DeveloperFolio    && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME         
GUSER=ionicfirebaseapp      &&  GREPO=flutter-app                    && APPNAME=FirebaseApp2      && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME           
GUSER=dvmjoshi              &&  GREPO=people                         && APPNAME=PeopleApp         && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME         
GUSER=TheAlphamerc          &&  GREPO=flutter-GitConnect             && APPNAME=GitConnect        && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME        
GUSER=ficiverson            &&  GREPO=clean-flutter                  && APPNAME=CleanFlutter      && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME            
GUSER=ninest                &&  GREPO=Shots                          && APPNAME=ShotsGame         && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME    
GUSER=mkiisoft              &&  GREPO=taphero                        && APPNAME=TapHeroGame       && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME     
GUSER=rnike                 &&  GREPO=tissuebox                      && APPNAME=TissueBoxGame     && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME      
GUSER=vintage               &&  GREPO=party_flutter                  && APPNAME=PartyGame         && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME    
GUSER=anupcowkur            &&  GREPO=Snake                          && APPNAME=SnakeGame         && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME    
GUSER=zackattack73          &&  GREPO=Random_Color                   && APPNAME=ColorGame         && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME     
GUSER=naro143               &&  GREPO=color_matching_game            && APPNAME=ColorMatchGame    && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME   
GUSER=Cifruktus             &&  GREPO=FlutterMinesweeper             && APPNAME=MineSweeperGame   && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME       
GUSER=ritsat                &&  GREPO=chess_board_game_example       && APPNAME=ChessGame         && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME  
GUSER=mono424               &&  GREPO=wp_chessboard                  && APPNAME=WpChessBoard      && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME       
GUSER=RuiMiguel             &&  GREPO=mario-flame                    && APPNAME=MarioGame         && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME    
GUSER=berkkl                &&  GREPO=Destini                        && APPNAME=DestiniGame       && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME      
GUSER=tylersavery           &&  GREPO=flutter-cardgame               && APPNAME=CardGame          && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME  
GUSER=flutterkit            &&  GREPO=zerker                         && APPNAME=AnimationLibrary  && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME       
GUSER=ecklf                 &&  GREPO=flutters                       && APPNAME=DemoGame          && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME    
GUSER=frideosapps           &&  GREPO=pair_game                      && APPNAME=PairGame          && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME     
GUSER=noob-hu-yaar          &&  GREPO=PacMan-mini                    && APPNAME=PacManGame        && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME      
GUSER=frideosapps           &&  GREPO=trivia_example                 && APPNAME=QuizApp2          && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME      
GUSER=PhilipsHue            &&  GREPO=flutter_reactive_ble           && APPNAME=ReactiveBleLib    && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME
GUSER=RivaanRanawat         &&  GREPO=flutter-amazon-clone-tutorial  && APPNAME=AmazonClone       && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME
GUSER=MaikuB                &&  GREPO=flutter_local_notifications    && APPNAME=LocalNotification && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME
GUSER=superlistapp          &&  GREPO=super_editor                   && APPNAME=EditorApp         && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME
GUSER=flutter-mapbox-gl     &&  GREPO=maps                           && APPNAME=GoogleMapsApp     && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME
GUSER=miguelpruivo          &&  GREPO=flutter_file_picker            && APPNAME=FilePickerApp     && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME
GUSER=imaNNeoFighT          &&  GREPO=fl_chart                       && APPNAME=ChartApp          && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME
GUSER=juliuscanute          &&  GREPO=qr_code_scanner                && APPNAME=QRCodeScannerApp  && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME
GUSER=bdlukaa               &&  GREPO=fluent_ui                      && APPNAME=FluentUIApp       && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME
GUSER=aleksanderwozniak     &&  GREPO=table_calendar                 && APPNAME=CalendarWidget    && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME
GUSER=gokadzev              &&  GREPO=Musify                         && APPNAME=MusicPlayerApp3   && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME
GUSER=juliansteenbakker     &&  GREPO=mobile_scanner                 && APPNAME=QRCodeScannerApp2 && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME
GUSER=KRTirtho              &&  GREPO=spotube                        && APPNAME=SpotifyClient     && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME
GUSER=invoiceninja          &&  GREPO=invoiceninja                   && APPNAME=InvoiceApp        && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME
GUSER=afgprogrammer         &&  GREPO=flutter_expense_manager        && APPNAME=ExpenseMngApp     && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME
GUSER=AdrianLopezGue        &&  GREPO=daruma-frontend                && APPNAME=ExpenseMngApp2    && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME
GUSER=debaghosh             &&  GREPO=Flutter-Profile-UI             && APPNAME=ProfileUIApp      && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME
GUSER=sabikrahat            &&  GREPO=invoice_pdf_generate           && APPNAME=InvoicePdfGenApp  && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME
GUSER=Amanullahgit          &&  GREPO=Photo-App-Project-Flutter      && APPNAME=FirebasePhotoApp  && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME
GUSER=AadrianLeo            &&  GREPO=Tictactoe-Multiplayer-Game     && APPNAME=MPTicTacToeApp    && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME
GUSER=fairfield-programming &&  GREPO=playground                     && APPNAME=KidsLearnProgApp  && rm -rif $APPNAME && git submodule add git@github.com:$GUSER/$GREPO.git  $APPNAME  

