GUSER=MarcusNg           &&  GREPO=flutter_spotify_ui             APPNAME=SpotifyClone    && rm -rif $APPNAME && git clone "https://github.com/$GUSER/$GREPO"".git" $APPNAME && rm -rif $GREPO/.git
GUSER=RivaanRanawat      &&  GREPO=instagram-flutter-clone        APPNAME=InstagramClone  && rm -rif $APPNAME && git clone "https://github.com/$GUSER/$GREPO"".git" $APPNAME && rm -rif $GREPO/.git
GUSER=abuanwar072        &&  GREPO=E-commerce-App-UI-Flutter      APPNAME=E-CommerceApp   && rm -rif $APPNAME && git clone "https://github.com/$GUSER/$GREPO"".git" $APPNAME && rm -rif $GREPO/.git
GUSER=Ronak99            &&  GREPO=Skype-Clone                    APPNAME=SkypeClone      && rm -rif $APPNAME && git clone "https://github.com/$GUSER/$GREPO"".git" $APPNAME && rm -rif $GREPO/.git
GUSER=roughike           &&  GREPO=inKino                         APPNAME=Inkino          && rm -rif $APPNAME && git clone "https://github.com/$GUSER/$GREPO"".git" $APPNAME && rm -rif $GREPO/.git
GUSER=iampawan           &&  GREPO=FlutterStackOverflowApp        APPNAME=StackOverFlow   && rm -rif $APPNAME && git clone "https://github.com/$GUSER/$GREPO"".git" $APPNAME && rm -rif $GREPO/.git
GUSER=nisrulz            &&  GREPO=flutter-examples               APPNAME=Examples        && rm -rif $APPNAME && git clone "https://github.com/$GUSER/$GREPO"".git" $APPNAME && rm -rif $GREPO/.git
GUSER=stonega            &&  GREPO=tsacdop                        APPNAME=PodcastPlayer   && rm -rif $APPNAME && git clone "https://github.com/$GUSER/$GREPO"".git" $APPNAME && rm -rif $GREPO/.git
GUSER=Hash-Studios       &&  GREPO=Prism                          APPNAME=PinterestClone  && rm -rif $APPNAME && git clone "https://github.com/$GUSER/$GREPO"".git" $APPNAME && rm -rif $GREPO/.git
GUSER=hungps             &&  GREPO=flutter_pokedex                APPNAME=Pokemon         && rm -rif $APPNAME && git clone "https://github.com/$GUSER/$GREPO"".git" $APPNAME && rm -rif $GREPO/.git
GUSER=iampawan           &&  GREPO=CryptoApp                      APPNAME=CryptoApp       && rm -rif $APPNAME && git clone "https://github.com/$GUSER/$GREPO"".git" $APPNAME && rm -rif $GREPO/.git
GUSER=searchy2           &&  GREPO=FlutterGames                   APPNAME=GameStore       && rm -rif $APPNAME && git clone "https://github.com/$GUSER/$GREPO"".git" $APPNAME && rm -rif $GREPO/.git
GUSER=rajayogan          &&  GREPO=flutterui-curveddesigns        APPNAME=NutritionApp    && rm -rif $APPNAME && git clone "https://github.com/$GUSER/$GREPO"".git" $APPNAME && rm -rif $GREPO/.git
GUSER=Santos-Enoque      &&  GREPO=uber_clone_with_flutter        APPNAME=UberClone       && rm -rif $APPNAME && git clone "https://github.com/$GUSER/$GREPO"".git" $APPNAME && rm -rif $GREPO/.git
GUSER=iampawan           &&  GREPO=GDG-DevFest-App                APPNAME=DevFest         && rm -rif $APPNAME && git clone "https://github.com/$GUSER/$GREPO"".git" $APPNAME && rm -rif $GREPO/.git
GUSER=abuanwar072        &&  GREPO=Furniture-App-UI-2-Flutter     APPNAME=FurnitureApp    && rm -rif $APPNAME && git clone "https://github.com/$GUSER/$GREPO"".git" $APPNAME && rm -rif $GREPO/.git
GUSER=theankurkedia      &&  GREPO=newsbuzz                       APPNAME=NewsAggregator  && rm -rif $APPNAME && git clone "https://github.com/$GUSER/$GREPO"".git" $APPNAME && rm -rif $GREPO/.git
GUSER=mcyos118           &&  GREPO=wordPress-flutter              APPNAME=WordPress       && rm -rif $APPNAME && git clone "https://github.com/$GUSER/$GREPO"".git" $APPNAME && rm -rif $GREPO/.git
GUSER=abuanwar072        &&  GREPO=Protfolio-Website-Flutter-Web  APPNAME=PortfolioWeb    && rm -rif $APPNAME && git clone "https://github.com/$GUSER/$GREPO"".git" $APPNAME && rm -rif $GREPO/.git
GUSER=Norbert515         &&  GREPO=BookSearch                     APPNAME=BookSearch      && rm -rif $APPNAME && git clone "https://github.com/$GUSER/$GREPO"".git" $APPNAME && rm -rif $GREPO/.git
GUSER=tavasolireza       &&  GREPO=Hangman-Game-Flutter           APPNAME=HangmanGame     && rm -rif $APPNAME && git clone "https://github.com/$GUSER/$GREPO"".git" $APPNAME && rm -rif $GREPO/.git
GUSER=rodydavis          &&  GREPO=gmail_clone                    APPNAME=GmailClone      && rm -rif $APPNAME && git clone "https://github.com/$GUSER/$GREPO"".git" $APPNAME && rm -rif $GREPO/.git
GUSER=rajayogan          &&  GREPO=FlutterUI---Emojis             APPNAME=EmojiUI         && rm -rif $APPNAME && git clone "https://github.com/$GUSER/$GREPO"".git" $APPNAME && rm -rif $GREPO/.git
GUSER=MarcusNg           &&  GREPO=flutter_facebook_responsive_ui APPNAME=FacebookClone   && rm -rif $APPNAME && git clone "https://github.com/$GUSER/$GREPO"".git" $APPNAME && rm -rif $GREPO/.git
GUSER=mdanics            &&  GREPO=fluttergram                    APPNAME=Fluttergram     && rm -rif $APPNAME && git clone "https://github.com/$GUSER/$GREPO"".git" $APPNAME && rm -rif $GREPO/.git
GUSER=Hritik-Chaurasia   &&  GREPO=Lavender                       APPNAME=VideoStream     && rm -rif $APPNAME && git clone "https://github.com/$GUSER/$GREPO"".git" $APPNAME && rm -rif $GREPO/.git
GUSER=MarcusNg           &&  GREPO=flutter_netflix_responsive_ui  APPNAME=NetflixUI       && rm -rif $APPNAME && git clone "https://github.com/$GUSER/$GREPO"".git" $APPNAME && rm -rif $GREPO/.git
GUSER=matthewtory        &&  GREPO=trinity-orientation-2018       APPNAME=TrinityCollege  && rm -rif $APPNAME && git clone "https://github.com/$GUSER/$GREPO"".git" $APPNAME && rm -rif $GREPO/.git
GUSER=FilledStacks       &&  GREPO=flutter-tutorials              APPNAME=TikTokUI        && rm -rif $APPNAME && git clone "https://github.com/$GUSER/$GREPO"".git" $APPNAME && rm -rif $GREPO/.git
GUSER=MarcusNg           &&  GREPO=flutter_chat_ui                APPNAME=ChatApp         && rm -rif $APPNAME && git clone "https://github.com/$GUSER/$GREPO"".git" $APPNAME && rm -rif $GREPO/.git
GUSER=MarcusNg           &&  GREPO=flutter_swarm_game             APPNAME=SwarmGame       && rm -rif $APPNAME && git clone "https://github.com/$GUSER/$GREPO"".git" $APPNAME && rm -rif $GREPO/.git
GUSER=MarcusNg           &&  GREPO=flutter_voice                  APPNAME=Speech2TextApp  && rm -rif $APPNAME && git clone "https://github.com/$GUSER/$GREPO"".git" $APPNAME && rm -rif $GREPO/.git
GUSER=boeledi            &&  GREPO=flutter_crush                  APPNAME=CrushGame       && rm -rif $APPNAME && git clone "https://github.com/$GUSER/$GREPO"".git" $APPNAME && rm -rif $GREPO/.git
GUSER=iampawan           &&  GREPO=FlutterWhatsAppClone           APPNAME=WhatsAppClone   && rm -rif $APPNAME && git clone "https://github.com/$GUSER/$GREPO"".git" $APPNAME && rm -rif $GREPO/.git
GUSER=MarcusNg           &&  GREPO=flutter_clubhouse_ui           APPNAME=ClubHouseClone  && rm -rif $APPNAME && git clone "https://github.com/$GUSER/$GREPO"".git" $APPNAME && rm -rif $GREPO/.git
GUSER=jesusrp98          &&  GREPO=spacex-go                      APPNAME=SpaceXGo        && rm -rif $APPNAME && git clone "https://github.com/$GUSER/$GREPO"".git" $APPNAME && rm -rif $GREPO/.git
GUSER=boyan01            &&  GREPO=flutter-tetris                 APPNAME=TetrisGame      && rm -rif $APPNAME && git clone "https://github.com/$GUSER/$GREPO"".git" $APPNAME && rm -rif $GREPO/.git
GUSER=mafreud            &&  GREPO=proximity                      APPNAME=Widgets         && rm -rif $APPNAME && git clone "https://github.com/$GUSER/$GREPO"".git" $APPNAME && rm -rif $GREPO/.git
GUSER=iampawan           &&  GREPO=FlutterTicTacToe               APPNAME=TicTacToeGame   && rm -rif $APPNAME && git clone "https://github.com/$GUSER/$GREPO"".git" $APPNAME && rm -rif $GREPO/.git
GUSER=deven98            &&  GREPO=FlutterSolitaire               APPNAME=SolitaireGame   && rm -rif $APPNAME && git clone "https://github.com/$GUSER/$GREPO"".git" $APPNAME && rm -rif $GREPO/.git
GUSER=rodydavis          &&  GREPO=flutter_piano                  APPNAME=PocketPiano     && rm -rif $APPNAME && git clone "https://github.com/$GUSER/$GREPO"".git" $APPNAME && rm -rif $GREPO/.git
GUSER=janoodleFTW        &&  GREPO=timy-messenger                 APPNAME=MessengerApp    && rm -rif $APPNAME && git clone "https://github.com/$GUSER/$GREPO"".git" $APPNAME && rm -rif $GREPO/.git
GUSER=sergiandreplace    &&  GREPO=flutter_planets_tutorial       APPNAME=PlanetEducation && rm -rif $APPNAME && git clone "https://github.com/$GUSER/$GREPO"".git" $APPNAME && rm -rif $GREPO/.git
GUSER=abuanwar072        &&  GREPO=E-commerce-Complete-Flutter-UI APPNAME=E-CommerceApp2  && rm -rif $APPNAME && git clone "https://github.com/$GUSER/$GREPO"".git" $APPNAME && rm -rif $GREPO/.git
GUSER=putraxor           &&  GREPO=flutter-login-ui               APPNAME=CleanLoginUI    && rm -rif $APPNAME && git clone "https://github.com/$GUSER/$GREPO"".git" $APPNAME && rm -rif $GREPO/.git
GUSER=iampawan           &&  GREPO=Flutter-Music-Player           APPNAME=MusicPlayerApp  && rm -rif $APPNAME && git clone "https://github.com/$GUSER/$GREPO"".git" $APPNAME && rm -rif $GREPO/.git
GUSER=abuanwar072        &&  GREPO=Recipe-App---Flutter-UI        APPNAME=RecipeApp       && rm -rif $APPNAME && git clone "https://github.com/$GUSER/$GREPO"".git" $APPNAME && rm -rif $GREPO/.git
GUSER=MDSADABWASIM       &&  GREPO=You                            APPNAME=WhatAboutYou    && rm -rif $APPNAME && git clone "https://github.com/$GUSER/$GREPO"".git" $APPNAME && rm -rif $GREPO/.git
GUSER=abuanwar072        &&  GREPO=Meditation-App                 APPNAME=MeditationApp   && rm -rif $APPNAME && git clone "https://github.com/$GUSER/$GREPO"".git" $APPNAME && rm -rif $GREPO/.git
GUSER=Soham-Rakhunde     &&  GREPO=workout_timer                  APPNAME=WorkoutTimerApp && rm -rif $APPNAME && git clone "https://github.com/$GUSER/$GREPO"".git" $APPNAME && rm -rif $GREPO/.git
GUSER=abuanwar072        &&  GREPO=Travel-App-UI-using-Flutter    APPNAME=TravelApp       && rm -rif $APPNAME && git clone "https://github.com/$GUSER/$GREPO"".git" $APPNAME && rm -rif $GREPO/.git
GUSER=MSzalek-Mobile     &&  GREPO=weight_tracker                 APPNAME=WeightTracker   && rm -rif $APPNAME && git clone "https://github.com/$GUSER/$GREPO"".git" $APPNAME && rm -rif $GREPO/.git
GUSER=abuanwar072        &&  GREPO=Movie-Info---Flutter-UI        APPNAME=MovieInfoApp    && rm -rif $APPNAME && git clone "https://github.com/$GUSER/$GREPO"".git" $APPNAME && rm -rif $GREPO/.git
GUSER=benoitletondor     &&  GREPO=Beer-Me-Up                     APPNAME=BeerMeup        && rm -rif $APPNAME && git clone "https://github.com/$GUSER/$GREPO"".git" $APPNAME && rm -rif $GREPO/.git
GUSER=Samaritan1011001   &&  GREPO=Trovami                        APPNAME=LiveLocShareApp && rm -rif $APPNAME && git clone "https://github.com/$GUSER/$GREPO"".git" $APPNAME && rm -rif $GREPO/.git
GUSER=brinesoftwares     &&  GREPO=Flutter-AI-Rubik-cube-Solver   APPNAME=RubikCubeSolver && rm -rif $APPNAME && git clone "https://github.com/$GUSER/$GREPO"".git" $APPNAME && rm -rif $GREPO/.git
GUSER=abuanwar072        &&  GREPO=Food-Ordering-App              APPNAME=FoodOrderingApp && rm -rif $APPNAME && git clone "https://github.com/$GUSER/$GREPO"".git" $APPNAME && rm -rif $GREPO/.git
GUSER=aaronoe            &&  GREPO=FlutterCinematic               APPNAME=CinematicApp    && rm -rif $APPNAME && git clone "https://github.com/$GUSER/$GREPO"".git" $APPNAME && rm -rif $GREPO/.git
GUSER=iampawan           &&  GREPO=fluttersignatureview           APPNAME=SignatureView   && rm -rif $APPNAME && git clone "https://github.com/$GUSER/$GREPO"".git" $APPNAME && rm -rif $GREPO/.git
GUSER=anuranBarman       &&  GREPO=2048                           APPNAME=Game2048        && rm -rif $APPNAME && git clone "https://github.com/$GUSER/$GREPO"".git" $APPNAME && rm -rif $GREPO/.git
GUSER=abuanwar072        &&  GREPO=Plant-App-Flutter-UI           APPNAME=PlantAppUI      && rm -rif $APPNAME && git clone "https://github.com/$GUSER/$GREPO"".git" $APPNAME && rm -rif $GREPO/.git
GUSER=redsolver          &&  GREPO=skyfeed                        APPNAME=SkyFeed         && rm -rif $APPNAME && git clone "https://github.com/$GUSER/$GREPO"".git" $APPNAME && rm -rif $GREPO/.git
GUSER=imSanjaySoni       &&  GREPO=Inshorts-Clone-The-News-App    APPNAME=InShortsClone   && rm -rif $APPNAME && git clone "https://github.com/$GUSER/$GREPO"".git" $APPNAME && rm -rif $GREPO/.git
GUSER=MDSADABWASIM       &&  GREPO=Toughest                       APPNAME=ToughestApp     && rm -rif $APPNAME && git clone "https://github.com/$GUSER/$GREPO"".git" $APPNAME && rm -rif $GREPO/.git
GUSER=GitJournal         &&  GREPO=GitJournal                     APPNAME=GoogleKeepClone && rm -rif $APPNAME && git clone "https://github.com/$GUSER/$GREPO"".git" $APPNAME && rm -rif $GREPO/.git
GUSER=ffactory-ofcl      &&  GREPO=fourinarow-app                 APPNAME=FourInARowGame  && rm -rif $APPNAME && git clone "https://github.com/$GUSER/$GREPO"".git" $APPNAME && rm -rif $GREPO/.git
GUSER=flutter            &&  GREPO=samples                        APPNAME=Samples         && rm -rif $APPNAME && git clone "https://github.com/$GUSER/$GREPO"".git" $APPNAME && rm -rif $GREPO/.git
GUSER=JideGuru           &&  GREPO=FlutterEbookApp                APPNAME=eBookApp        && rm -rif $APPNAME && git clone "https://github.com/$GUSER/$GREPO"".git" $APPNAME && rm -rif $GREPO/.git